version: '3.9'

services:
  backend:
    build: .
    container_name: backend_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/backend/src         
      - ./package.json:/backend/package.json
      - ./tsconfig.json:/backend/tsconfig.json
      - ./nodemon.json:/backend/node
    command: npm run dev      
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: inamfalahuddin_fdtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data   # hanya data DB

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
